config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'places#index'

  resources :places do
    collection do
      get :filter_by_changing_table
      get :filter_by_high_chair
      get :filter_by_toy
      get :filter_by_play_area
    end
  end

  get '/privacy', to: 'pages#privacy', as: 'privacy'
  get '/terms', to: 'pages#terms', as: 'terms'
  get '/cookies', to: 'pages#cookies', as: 'cookies'
  get '/about', to: 'pages#about', as: 'about'

  resources :types, only: [:index, :new, :create, :edit, :update, :destroy]

  # resources :contacts, only: [:new, :create]

  get "/contact_us", to: "contacts#new", as: 'contact_us'
  post "/contacts", to: "contacts#create"
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:edit, :update, :destroy]

  def index
    @types = policy_scope(Type)
  end

  def new
    @type = Type.new
    authorize @type
  end

  def create
    @type = Type.new(type_params)
    authorize @type
    if @type.save
      redirect_to types_path, notice: 'Type was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @type.update(type_params)
    if @type.save
      redirect_to types_path, notice: 'Type was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @type.destroy
    redirect_to types_path(@type)
  end

  private

  def set_type
    @type = Type.find(params[:id])
    authorize @type
  end

  def type_params
    params.require(:type).permit(:name)
  end
end

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |t| %>

  <div class="form-inputs">
    <p><%= t.input :name %></p>
  </div>

  <div class="form-actions mt-5">
    <%= link_to 'Cancel', types_path, :class => 'btn-n btn-n-secondary mr-auto' %>
    <%= t.button :submit, :class => 'btn-n btn-n-primary' %>
  </div>
<% end %>

app/views/types/edit.html.erb
<div class="form-container">
  <div class="account-page-form-box">
    <h1 class="sign-title">Update Type</h1>
      <%= render 'form', type: @type %>
  </div>
</div>

app/views/types/index.html.erb
<div class="form-container">
  <div class="account-page-form-box">
      <!-- <div class="place-card-details"> -->
        <h1 class="mt-5 mb-5">Type of places</h1>
        <% @types.each do |t| %>
          <p class="card-type mb-3">
            - <strong><%= t.name %></strong>
            / <%= link_to 'Edit', edit_type_path(t), :class => 'no-decor' %>
            / <%= link_to "✖️", t, method: :delete, data: {confirm: "Are you sure?"} %>
          </p>
        <% end %>
        <h4 class="mt-5 mb-5"><%= link_to 'Create Type', new_type_path, :class => 'no-decor-color' %></h4>
      <!-- </div> -->
  </div>
</div>

app/views/types/new.html.erb
<div class="form-container">
  <div class="account-page-form-box">
    <h1 class="sign-title">Create Type</h1>
    <%= render 'form', type: @type %>
  </div>
</div>