config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'places#index'

  resources :places do
    collection do
      get :filter_by_changing_table
      get :filter_by_high_chair
      get :filter_by_toy
      get :filter_by_play_area
    end
  end

  get '/privacy', to: 'pages#privacy', as: 'privacy'
  get '/terms', to: 'pages#terms', as: 'terms'
  get '/cookies', to: 'pages#cookies', as: 'cookies'
  get '/about', to: 'pages#about', as: 'about'

  resources :types, only: [:index, :new, :create, :edit, :update, :destroy]

  # resources :contacts, only: [:new, :create]

  get "/contact_us", to: "contacts#new", as: 'contact_us'
  post "/contacts", to: "contacts#create"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show pl-4 pr-4" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show pl-4 pr-4" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="sub-footer">
    <div class="sub-footer-title">Company</div>
    <div><%= link_to 'About Us', about_path, class: "no-decor-color" %></div>
  </div>
  <div class="sub-footer">
    <div class="sub-footer-title">Support</div>
    <div><%= link_to 'Contact', contact_us_path, class: "no-decor-color" %></div>
    <p><a class="no-decor-color" target="_blank" href="https://apps.apple.com/de/app/nappies/id1522079929?l=en">iOS App</a></p>
  </div>
  <div class="sub-footer">
    <div class="sub-footer-title">Corporate Policy</div>
    <div><%= link_to 'Privacy Policy', privacy_path, class: "no-decor-color" %></div>
    <div><%= link_to 'Terms & Conditions', terms_path, class: "no-decor-color" %></div>
    <div><%= link_to 'Cookies', cookies_path, class: "no-decor-color" %></div>
  </div>
  <div class="footer-links">
    <a class="no-decor" href="https://apps.apple.com/de/app/nappies/id1522079929?l=en" target="_blank"><%= image_tag "iOS-badge-black.jpg", class: 'ios-badge' %></i></a>
    <a class="no-decor-color" href="https://www.instagram.com/nappiesapp/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a class="no-decor-color" href="#"><i class="fab fa-facebook"></i></a>
    <a class="no-decor-color" href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <div>© NAPPIES 2020</div>
  </div>
</div>

app/views/shared/_navbar-desktop.html.erb
<div class="navbar-desktop">
  <div class="logo-desktop">
    <%= link_to "NAPPIES", places_path, class: "logo-text" %>
  </div>
  <div class="search-desktop">
    <%= render 'shared/search-desktop' %>
  </div>
  <div class="content-navbar">
    <% if user_signed_in? %>
      <div>
        <% if current_user.admin? %>
          <%= link_to "Create A Place", new_place_path, class: "no-decor-color" %>
        <% else %>
          <a class="no-decor-color" target="_blank" href="mailto:nappiesapp@gmail.com">Recommend A Place</a>
        <% end %>
      </div>
      <div>
        <%= link_to current_user.username.upcase, edit_user_registration_path, class: "no-decor-color content-right" %>
      </div>
    <% else %>
      <div>
        <%= link_to "Login", new_user_session_path, class: "no-decor-color" %>
      </div>
      <div>
        <strong><%= link_to "SIGN UP", new_user_registration_path, class: "no-decor-color content-right" %></strong>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar-mobile.html.erb
<div class="navbar-mobile">
  <!-- DROPDOWN -->
  <div class="dropdown-mobile">
    <div class="list-navbar"><i class="fas fa-bars"></i></div>
    <div class="list-navbar-x"><i class="fas fa-times"></i></div>
    <div class="dropdown-list">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to current_user.username.upcase, edit_user_registration_path, :class => 'no-decor-dropdown' %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Create A Place", new_place_path, :class => 'no-decor-dropdown' %></li>
          <% else %>
            <li><a class="no-decor-color" target="_blank" href="mailto:nappiesapp@gmail.com">Recommend A Place</a></li>
          <% end %>
          <%# if current_user.admin? %>
            <%# if current_user[:photo] %>
              <!-- <li><%#= cl_image_tag current_user.photo.key, height: 400, crop: :fill, class: "avatar" %></li> -->
            <%# else %>
              <!-- <li><%#= image_tag "profile-icon.png", height: 400, crop: :fill, class: "avatar" %></li> -->
            <%# end %>
          <%# end %>
        <% else %>
            <li><%= link_to "Login", new_user_session_path, :class => 'no-decor-dropdown' %></li>
            <li><strong><%= link_to "SIGN UP", new_user_registration_path, :class => 'no-decor-dropdown' %></strong></li>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- SEARCH -->
  <div class="search-mobile">
    <button class="search-button-navbar"><i class="fas fa-search"></i></button>
    <button class="search-button-x"><i class="fas fa-times"></i></button>
    <div class="search-form-mobile">
      <%= form_for :search, url: places_path, class: "search-form form-container", method: :get do %>
        <div class="search-box-mobile">
            <%= text_field_tag :query, params[:query],
              class: "search-input-mobile",
              placeholder: "City, place name, type..."%>
          <%= select_tag "facility", options_for_select(['Select Facility',
                    'Changing Table',
                    'Toy',
                    'High Chair',
                    'Play Area']), class: "select2 search-select-mobile" %>
          <div class="search-popup-footer">
            <button type="submit" class="search-submit-navbar"><i class="fas fa-search"></i> search</button>
            <!-- <button class="search-submit-navbar cancel-button">Close</button> -->
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="logo-search">
    <%= link_to "NAPPIES", places_path, class: "navbar-brand logo-text" %>
  </div>
  <div class="search-mobile d-block d-sm-none">
    <button type="button" class="search-button-mobile" data-toggle="modal" data-target="#loginModal">
      <i class="fas fa-search"></i>
    </button>
    <div class="modal"id="loginModal" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <%= form_for :search, url: places_path, class: "search-form", method: :get do %>
              <div class="search-box-mobile">
                <%= text_field_tag :query, params[:query],
                  class: "search-input-mobile",
                  placeholder: "City, place name, type..."%>
                <%= select_tag "facility", options_for_select(['Select Facility',
                          'Diaper',
                          'Toy',
                          'High Chair',
                          'Play Area']), class: "search-select-mobile" %>
                <div class="search-popup-footer">
                  <button class="btn" type="button" data-dismiss="modal" >Close</button>
                  <button type="submit" class="search-submit-mobile">Search</button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="search-desktop">
    <%= render 'shared/search-desktop' %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <% if current_user.admin? %>
            <%= link_to "Create A Place", new_place_path, class: "nav-link" %>
          <% else %>
            <a class="no-decor-color nav-link" target="_blank" href="mailto:nappiesapp@gmail.com">Recommend A Place</a>
            <%#= link_to "Recommend A Place", edit_user_registration_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.username.upcase, edit_user_registration_path, class: "nav-link" %>
          <%#= link_to "Account", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "My Account", account_path(current_user), class: "nav-link" %>
          <%#= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'no-decor-color nav-link' %>
        </li>
        <% if current_user.admin? %>
          <% if current_user[:photo] %>
            <%= cl_image_tag current_user.photo.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "profile-icon.png", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right dp-down-r" aria-labelledby="navbarDropdown">
            <%= link_to "Type", types_path, class: "dropdown-item" %>
          </div>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <strong><%= link_to "SIGN UP", new_user_registration_path, class: "nav-link" %></strong>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_bottom.html.erb
<div class="navbar-bottom">
  <div class="navbar-bottom-box">
    <div class="navbar-bottom-items"><%= link_to image_tag('icon-all.png'), places_path, class: 'navbar-icon' %></div>
    <div class="navbar-bottom-items"><%= link_to image_tag('icon-diaper.png'), filter_by_changing_table_places_path, class: 'navbar-icon' %></div>
    <div class="navbar-bottom-items"><%= link_to image_tag('icon-high-chair.png'), filter_by_high_chair_places_path, class: 'navbar-icon' %></div>
    <div class="navbar-bottom-items"><%= link_to image_tag('icon-toy.png'), filter_by_toy_places_path, class: 'navbar-icon' %></div>
    <div class="navbar-bottom-items"><%= link_to image_tag('icon-play-area.png'), filter_by_play_area_places_path, class: 'navbar-icon' %></div>
  </div>
</div>

<!--
<div class="navbar-bottom">
  <div class="navbar-bottom-box">
    <div class="child"><%#= link_to image_tag('icon-all.png'), places_path, class: 'navbar-icon' %></div>
    <div class="child"><%#= link_to image_tag('icon-diaper.png'), filter_by_changing_table_places_path, class: 'navbar-icon' %></div>
    <div class="child"><%#= link_to image_tag('icon-high-chair.png'), filter_by_changing_table_places_path, class: 'navbar-icon' %></div>
    <div class="child"><%#= link_to image_tag('icon-toy.png'), filter_by_changing_table_places_path, class: 'navbar-icon' %></div>
    <div class="child"><%#= link_to image_tag('icon-play-area.png'), filter_by_changing_table_places_path, class: 'navbar-icon' %></div>
  </div>
</div>
 -->

app/views/shared/_navbar_desktop.html.erb
<div class="navbar-desktop">
  <div class="content-navbar">
    <% if user_signed_in? %>
      <div>
        <% if current_user.admin? %>
          <%= link_to "Create A Place", new_place_path, class: "no-decor-color" %>
          <%= link_to "Type", types_path, class: "no-decor-color content-right" %>
        <% else %>
          <div><%= link_to 'Recommend A Place', contact_us_path, :class => 'no-decor-color' %></div>
        <% end %>
      </div>
    <% else %>
      <div><%= link_to 'Recommend A Place', contact_us_path, :class => 'no-decor-color' %></div>
    <% end %>
  </div>

  <div class="logo-desktop">
    <%= link_to "NAPPIES", places_path, class: "logo-text" %>
  </div>

  <div class="content-navbar">
    <% if user_signed_in? %>
      <div class="search-icon"><i class="fas fa-search"></i></div>
      <div>
        <%= link_to current_user.username.upcase, edit_user_registration_path, class: "no-decor-color content-right" %>
      </div>
      <div>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'no-decor-color content-right' %>
      </div>
    <% else %>
      <div class="search-icon"><i class="fas fa-search"></i></div>
      <div>
        <%= link_to "Login", new_user_session_path, class: "no-decor-color content-right" %>
      </div>
      <div>
        <%= link_to "SIGN UP", new_user_registration_path, class: "no-decor-color content-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_mobile.html.erb
<div class="navbar-mobile">
  <!-- DROPDOWN -->
  <div class="dropdown-mobile">
    <div class="list-navbar"><i class="fas fa-bars"></i></div>
    <div class="list-navbar-x"><i class="fas fa-times"></i></div>
    <div class="dropdown-list">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to current_user.username.upcase, edit_user_registration_path, :class => 'no-decor-color' %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Create A Place", new_place_path, :class => 'no-decor-color' %></li>
            <li><%= link_to "Type", types_path, :class => 'no-decor-color' %></li>
          <% else %>
            <li><%= link_to 'Recommend A Place', contact_us_path, :class => 'no-decor-color' %></li>
          <% end %>
          <li><strong><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'no-decor-color' %></strong></li>
          <%# if current_user.admin? %>
            <%# if current_user[:photo] %>
              <!-- <li><%#= cl_image_tag current_user.photo.key, height: 400, crop: :fill, class: "avatar" %></li> -->
            <%# else %>
              <!-- <li><%#= image_tag "profile-icon.png", height: 400, crop: :fill, class: "avatar" %></li> -->
            <%# end %>
          <%# end %>
        <% else %>
            <!-- <li><a class="no-decor-color" target="_blank" href="mailto:nappiesapp@gmail.com">Recommend A Place</a></li> -->
            <li><%= link_to 'Recommend A Place', contact_us_path, :class => 'no-decor-color' %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'no-decor-color' %></li>
            <li><strong><%= link_to "SIGN UP", new_user_registration_path, :class => 'no-decor-color' %></strong></li>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- LOGO -->
  <div class="logo-mobile">
    <%= link_to "NAPPIES", places_path, class: "m-logo-text" %>
  </div>

  <!-- SEARCH -->
  <div class="search-mobile">
    <button class="search-button-navbar"><i class="fas fa-search"></i></button>
    <button class="search-button-x"><i class="fas fa-times"></i></button>
    <div class="search-form-mobile">

      <%= simple_form_for :search, url: places_path, method: "GET", html: { class: 'search-form' } do |f| %>
        <div class="search-box">
          <%= f.input :query, label: false, placeholder: "City, place name, type...", input_html: { class: "search-input-mobile" } %>
          <%= f.input :type, as: :select, :collection => Type.limit(10), label: false, prompt: "Select Type", input_html: { class: "select2 search-select-mobile" }  %>
          <%= f.input :changing_table, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "input-changing-table" } %>
          <%= f.input :high_chair, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "input-high-chair" } %>
          <%= f.input :toy, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "input-toy" } %>
          <%= f.input :play_area, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "input-play-area" } %>
          <button type="submit" class="search-submit-navbar"><i class="fas fa-search"></i> search</button>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_place_facility_form.html.erb
<%= simple_form_for [@place, @place_facility] do |f| %>
  <%#= p.error_notification %>
  <%#= p.error_notification message: p.object.errors[:base].to_sentence if p.object.errors[:base].present? %>

  <div class="form-inputs">
    <p><%= f.association :facility %></p>
  </div>

  <div class="form-actions mt-5">
    <%= f.button :submit, :class => 'account-submit' %>
    <%= link_to 'Cancel', places_path, :class => 'no-decor-color' %>
  </div>
<% end %>

app/views/shared/_search-desktop.html.erb
<%= form_for :search, url: places_path, class: "search-form", method: :get do %>
  <div class="search-box">
      <%= text_field_tag :query, params[:query],
        class: "search-input placeholder-search",
        placeholder: "City, place name, type..."%>
      <%= select_tag "facility", options_for_select(['Select Facility',
                'Changing Table',
                'Toy',
                'High Chair',
                'Play Area']), class: "select2 search-select" %>
      <%#= submit_tag "🔎", class: "search-submit"  %>
      <button type="submit" class="search-submit"><i class="fas fa-search"></i></button>
  </div>
<% end %>

app/views/shared/_search_desktop.html.erb
 <div class="search-desktop">
   <%= simple_form_for :search, url: places_path, method: "GET", html: { class: 'search-form' } do |f| %>
    <div class="search-box">
      <%= f.input :query, label: false, placeholder: "City, place name, type...", input_html: { class: "search-input placeholder-search" } %>
      <%= f.input :type, as: :select, :collection => Type.limit(10), label: false, prompt: "Select Type", input_html: { class: "select2 search-select" }  %>
      <%= f.input :changing_table, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "d-input-changing-table" } %>
      <%= f.input :high_chair, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "d-input-high-chair" } %>
      <%= f.input :toy, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "d-input-toy" } %>
      <%= f.input :play_area, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: "d-input-play-area" } %>
      <button type="submit" class="search-submit"><i class="fas fa-search"></i></button>
    </div>
  <% end %>
 </div>