config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'places#index'

  resources :places do
    collection do
      get :filter_by_changing_table
      get :filter_by_high_chair
      get :filter_by_toy
      get :filter_by_play_area
    end
  end

  get '/privacy', to: 'pages#privacy', as: 'privacy'
  get '/terms', to: 'pages#terms', as: 'terms'
  get '/cookies', to: 'pages#cookies', as: 'cookies'
  get '/about', to: 'pages#about', as: 'about'

  resources :types, only: [:index, :new, :create, :edit, :update, :destroy]

  # resources :contacts, only: [:new, :create]

  get "/contact_us", to: "contacts#new", as: 'contact_us'
  post "/contacts", to: "contacts#create"
end

app/models/place.rb
class Place < ApplicationRecord
  # keep the default scope first (if any)
  scope :filter_by_changing_table, -> { where(changing_table: true) }
  scope :filter_by_high_chair, -> { where(high_chair: true) }
  scope :filter_by_toy, -> { where(toy: true) }
  scope :filter_by_play_area, -> { where(play_area: true) }

  # followed by association macros
  belongs_to :user
  belongs_to :type
  # has_many :facilities, through: :place_facilities
  # has_many :place_facilities, dependent: :destroy
  has_one_attached :photo1
  has_one_attached :photo2
  has_one_attached :photo3
  has_one_attached :photo4
  has_one_attached :photo5


  # and validation macros
  validates :name, presence: true
  validates :address, presence: true
  validates :type_id, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :address ],
    associated_against: {
      type: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  # def self.search_by(search_term)
  #   where("LOWER(address) LIKE :search_term", search_term: "%#{search_term.downcase}%")
  # end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, except: [ :new, :create, :edit, :update, :destroy ]
  before_action :set_place, only: [ :show, :edit, :update, :destroy ]

  def index
    @places = policy_scope(Place)
    @places = Place.all
    # @places = @places.sample
    @types = Type.order(name: :asc)

    @places = @places.joins(:type).where(types: { id: params[:search][:type] }) if params[:search] && params[:search][:type].present?
    @places = Place.global_search(params[:search][:query]) if params[:search] && params[:search][:query].present?
    @places = @places.filter_by_changing_table if params[:search] && params[:search][:changing_table] == 'true'
    @places = @places.filter_by_high_chair if params[:search] && params[:search][:high_chair] == 'true'
    @places = @places.filter_by_toy if params[:search] && params[:search][:toy] == 'true'
    @places = @places.filter_by_play_area if params[:search] && params[:search][:play_area ] == 'true'

    if @places.present?
      @places = @places.shuffle
    else
      @places = Place.geocoded
      @response = "Sorry, no results found."
    end

    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "map_box", locals: { place: place }),
        # infoWindow: { content: render_to_string(partial: "/places/map_box", locals: { place: place }) },
        image_url: helpers.asset_url('map-pin-baby.png')
      }
    end
  end

  def filter_by_changing_table
    @places = Place.filter_by_changing_table
    skip_authorization

    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "map_box", locals: { place: place }),
        # infoWindow: { content: render_to_string(partial: "/places/map_box", locals: { place: place }) },
        image_url: helpers.asset_url('map-pin-baby.png')
      }
    end

    render 'places/index'
  end

  def filter_by_high_chair
    @places = Place.filter_by_high_chair
    skip_authorization

    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "map_box", locals: { place: place }),
        # infoWindow: { content: render_to_string(partial: "/places/map_box", locals: { place: place }) },
        image_url: helpers.asset_url('map-pin-baby.png')
      }
    end

    render 'places/index'
  end

  def filter_by_toy
    @places = Place.filter_by_toy
    skip_authorization

    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "map_box", locals: { place: place }),
        # infoWindow: { content: render_to_string(partial: "/places/map_box", locals: { place: place }) },
        image_url: helpers.asset_url('map-pin-baby.png')
      }
    end

    render 'places/index'
  end

  def filter_by_play_area
    @places = Place.filter_by_play_area
    skip_authorization

    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "map_box", locals: { place: place }),
        # infoWindow: { content: render_to_string(partial: "/places/map_box", locals: { place: place }) },
        image_url: helpers.asset_url('map-pin-baby.png')
      }
    end

    render 'places/index'
  end

  def show
    @markers = Array.new
    @markers << { lat: @place.latitude,
                  lng: @place.longitude,
                  image_url: helpers.asset_url('map-pin-baby.png')
                 }
  end

  def new
    @place = Place.new
    authorize @place
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    authorize @place
    if @place.save
      redirect_to @place
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_to @place
    else
      render :edit
    end
  end

  def destroy
    @place.destroy
    redirect_to places_url
  end

  private

  def set_place
    @place = Place.find(params[:id])
    authorize @place
  end

  def place_params
    params.require(:place).permit(:name, :address, :user_id, :type_id, :changing_table, :toy, :high_chair, :play_area, :photo1, :photo2, :photo3, :photo4, :photo5)
  end
end

app/views/places/_form.html.erb
<%= simple_form_for(place) do |p| %>
  <%= p.error_notification %>
  <%= p.error_notification message: p.object.errors[:base].to_sentence if p.object.errors[:base].present? %>

  <div class="form-inputs">
    <p><%= p.input :name %></p>
    <p><%= p.input :address, :id => 'flat_address' %></p>
    <label>Type of place *</label>
    <div><%= p.association :type, label: false, include_blank: "Select type of place", input_html: { class: "select2 rounded-sm" }, include_hidden: false  %></div>
    <label>Facility *</label>
    <div class="form-facility-box">
      <p><%= p.input :changing_table, as: :radio_buttons %></p>
      <p><%= p.input :toy, as: :radio_buttons %></p>
      <p><%= p.input :high_chair, as: :radio_buttons %></p>
      <p><%= p.input :play_area, as: :radio_buttons %></p>

      <%#= p.input :changing_table, as: :boolean, checked_value: true, unchecked_value: false %>
      <%#= p.input :toy, as: :boolean, checked_value: true, unchecked_value: false %>
      <%#= p.input :high_chair, as: :boolean, checked_value: true, unchecked_value: false %>
      <%#= p.input :play_area, as: :boolean, checked_value: true, unchecked_value: false %>
    </div>
    <label>Photos</label>
    <div class="form-facility-box">
      <p><%= p.input :photo1, as: :file %></p>
      <p><%= p.input :photo2, as: :file %></p>
      <p><%= p.input :photo3, as: :file %></p>
      <p><%= p.input :photo4, as: :file %></p>
      <p><%= p.input :photo5, as: :file %></p>
    </div>
  </div>

  <div class="form-actions mt-5">
    <%= link_to 'Cancel', places_path, :class => 'btn-n btn-n-secondary mr-auto' %>
    <%= p.button :submit, :class => 'btn-n btn-n-primary' %>
  </div>
<% end %>

app/views/places/_info_window.html.erb
<div class="map-info">
  <%= link_to place_path(place), class:"link", :action => 'go' do %>
    <% if place.photo1.attached? %>
      <%= cl_image_tag place.photo1.key, class: 'map-image' %>
    <% else %>
      <%= image_tag "place-icon.png", class: 'map-image' %>
    <% end %>
    <div class="map-card-details">
      <% if place.type_id.nil? %>
        <p class="map-type">none</p>
      <% else %>
        <p class="map-type"><%= place.type.name %></p>
      <% end %>
      <p class="map-name"><%= place.name %></p>
    </div>
  <% end %>
</div>

app/views/places/_map_box.html.erb
<div class="map-info-card">
  <%= link_to place_path(place), class:"link", :action => 'go' do %>
  <div>
    <% if place.photo1.attached? %>
      <%= cl_image_tag place.photo1.key, width: 250, height: 150, crop: :fill, class: 'map-image' %>
    <% else %>
      <%= image_tag "place-icon-landscape.png", width: 250, height: 150, crop: :fill, class: 'map-image' %>
    <% end %>
  </div>
  <div class="map-info-card-details">
    <div>
      <div class="map-info-type"><%= place.type.name %></div>
      <div class="map-info-name"><%= place.name %></div>
    </div>
    <div class="map-info-facility">
      <div class="map-info-facility-icons mr-1">
        <% if place.changing_table == true %>
        <%= image_tag "icon-diaper.png", class: 'map-info-facility-icon' %>                    <% end %>
      </div>
      <div class="map-info-facility-icons mr-1">
        <% if place.high_chair == true %>
        <%= image_tag "icon-high-chair.png", class: 'map-info-facility-icon' %>
        <% end %>
      </div>
      <div class="map-info-facility-icons mr-1">
        <% if place.toy == true %>
        <%= image_tag "icon-toy.png", class: 'map-info-facility-icon' %>
        <% end %>
      </div>
      <div class="map-info-facility-icons">
        <% if place.play_area == true %>
        <%= image_tag "icon-play-area.png", class: 'map-info-facility-icon' %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/places/edit.html.erb
<div class="form-container">
  <div class="account-page-form-box">
    <h1 class="sign-title">Update Place</h1>
      <%= render 'form', place: @place %>
  </div>
</div>

app/views/places/index.html.erb
<div class="nappies-container">
  <% if !@response.present? %>
    <div class="btn-map-box">
      <a class="btn-map" href="#map"><i class="fas fa-map-marked-alt"></i></a>
    </div>
    <div class="btn-list-box">
      <a class="btn-list" href="#all-cards"><i class="fas fa-list"></i></a>
    </div>
    <div id="all-cards" class="index-cards">
      <div class="nappies-cards container-cards">
        <% @places.each do |place| %>
          <div class="nappies-card">
            <%= link_to place_path(place), class:"link", :action => 'go' do %>
            <!-- <div> -->
              <% if place.photo1.attached? %>
              <%= cl_image_tag place.photo1.key, width: 270, height: 170, crop: :fill, class: 'card-image' %>
              <% else %>
              <%= image_tag "place-icon-landscape.png", width: 270, height: 170, crop: :fill, class: 'card-image' %>
              <% end %>
            <!-- </div> -->
            <div class="card-details">
              <div>
                <div class="card-type"><%= place.type.name %></div>
                <div class="card-name"><%= place.name %></div>
              </div>
              <div class="card-facility">
                <div class="mr-1">
                  <% if place.changing_table == true %>
                  <%= image_tag "icon-diaper.png", class: 'card-facility-icon' %>                    <% end %>
                </div>
                <div class="mr-1">
                  <% if place.high_chair == true %>
                  <%= image_tag "icon-high-chair.png", class: 'card-facility-icon' %>
                  <% end %>
                </div>
                <div class="mr-1">
                  <% if place.toy == true %>
                  <%= image_tag "icon-toy.png", class: 'card-facility-icon' %>
                  <% end %>
                </div>
                <div>
                  <% if place.play_area == true %>
                  <%= image_tag "icon-play-area.png", class: 'card-facility-icon' %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div
      id="map", class="index-map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <% else %>

    <div class="response">
      <%= @response %>
      <div></div>
      <!-- <div>It seems we can’t find any results based on your search.</div> -->
    </div>

  <% end %>
</div>

app/views/places/new.html.erb
<div class="form-container">
  <div class="account-page-form-box">
    <h1 class="sign-title">Create Place</h1>
    <%= render 'form', place: @place %>
  </div>
</div>

app/views/places/noresult.html.erb
<br>
<br>
<br>
<br>
<h1 class="mb-5">No Result!</h1>

app/views/places/show.html.erb
<div class="nappies-container">
  <div class="show-images">
  <% if @place.photo1.attached? %>
    <%= cl_image_tag @place.photo1.key, height: 400, crop: :fill, class: 'show-img' %>
  <% else %>
    <%= image_tag "place-icon-landscape.png", height: 400, crop: :fill, class: 'show-img' %>
  <% end %>

  <% if @place.photo2.attached? %>
    <%= cl_image_tag @place.photo2.key, height: 400, crop: :fill, class: 'show-img' %>
  <% else %>
    <%= image_tag "place-icon.png", height: 400, crop: :fill, class: 'show-img' %>
  <% end %>

  <% if @place.photo3.attached? %>
    <%= cl_image_tag @place.photo3.key, height: 400, crop: :fill, class: 'show-img' %>
  <% else %>
    <%= image_tag "place-icon.png", height: 400, crop: :fill, class: 'show-img' %>
  <% end %>

  <% if @place.photo4.attached? %>
    <%= cl_image_tag @place.photo4.key, height: 400, crop: :fill, class: 'show-img' %>
  <% else %>
    <%= image_tag "place-icon.png", height: 400, crop: :fill, class: 'show-img' %>
  <% end %>

  <% if @place.photo5.attached? %>
    <%= cl_image_tag @place.photo5.key, height: 400, crop: :fill, class: 'show-img' %>
  <% else %>
    <%= image_tag "place-icon.png", height: 400, crop: :fill, class: 'show-img' %>
  <% end %>
</div>
<div class="show-details-box">
  <div class="show-detail-box">

    <% if @place.type_id.nil? %>
     <div class="show-type">none</p>
    <% else %>
     <div class="show-type"><%= @place.type.name %></div>
    <% end %>


    <div class="show-title"><%= @place.name %></div>
    <div class="show-address"><%= @place.address %></div>
    <div class="show-facility">
      <div class="facility-details">
        <% if @place.changing_table == true %>
          <%= image_tag "icon-diaper.png", class: 'facility-image' %>
          <div class="facility-name">Changing Table</div>
        <% end %>
      </div>
      <div class="facility-details">
        <% if @place.high_chair == true %>
          <%= image_tag "icon-high-chair.png", class: 'facility-image' %>
          <div class="facility-name">High Chair</div>
        <% end %>
      </div>
      <div class="facility-details">
        <% if @place.toy == true %>
          <%= image_tag "icon-toy.png", class: 'facility-image' %>
          <div class="facility-name">Toys</div>
        <% end %>
      </div>
      <div class="facility-details">
        <% if @place.play_area == true %>
          <%= image_tag "icon-play-area.png", class: 'facility-image' %>
          <div class="facility-name">Play Area</div>
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <div class="admin-box">
          <div>ADMIN</div>
            <div class="admin-authorize">
              <% if policy(@place).edit? %>
                <div><i class="far fa-edit"></i> <%= link_to 'Edit', edit_place_path(@place), :class => 'no-decor' %></div>
              <% end %>
              <div> | </div>
              <% if policy(@place).destroy? %>
                <div><i class="far fa-trash-alt"></i> </i><%= link_to 'Destroy', place_path(@place.id), :class => 'no-decor', method: :delete, data: {confirm: "Are you sure?"} %></div>
              <% end %>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div
    id="map", class="show-map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="show-content-footer">
    <div class="btn-n btn-n-secondary mr-auto"><i class="fas fa-arrow-left"></i>  <%= link_to 'Back', root_path, :class => 'no-decor' %></div>
    <a class="btn-n btn-n-primary no-decor ml-1" href="https://maps.google.com/?q=<%= @place.latitude %>,<%= @place.longitude %>" target="_blank">Directions</a>
  </div>
</div>
</div>